# Generated by Django 5.0.4 on 2025-02-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0022_chestflymachine_declinebenchpress_hipthrust_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Romaniandeadlift2',
            new_name='Romaniandeadlift',
        ),
    ]
